---
title: "AggregationProject_Heritability_geneticCOV"
author: "KYJ"
date: "20/10/2025"
output: html_document
---
```{r}
library(ggplot2)
library(dplyr)
library(tidyverse)
library(patchwork)
library(boot)
library(lme4)
library(futile.logger)
library(sommer)
library(data.table)
library(smartsnp)
```

```{r}
mean_agg <- read.csv('/Volumes/YounJaeSSD/2021_MaxPlanck/laptop/YJ_writing/Evo_Agg_paper/V2/code/files/wildstrains_herit_df.csv')
processed_data <- mean_agg[,c("Strain","magnitude","timescale")]
colnames(processed_data) <- c("strain", "mean_agg","agg_timescale")
processed_data
```

```{r}
geno_matrix <- readLines("/Volumes/YounJaeSSD/2021_MaxPlanck/laptop/YJ_Codes/CeNDR_heritability/Kang/input_data/output/260804_200strains/Genotype_Matrix.tsv")
#geno_matrix <- readLines("/Users/ykang/YJ_writing/Evo_Agg_paper/V2/Genotype_Matrix_200strains.tsv")
geno_matrix <- stringr::str_replace_all(geno_matrix, "t", "")  #getting rid of "t" tap separator.
geno_matrix <- textConnection(geno_matrix)
geno_matrix <- read.delim(geno_matrix, sep="\\") %>% na.omit()
geno_matrix
```

```{r}
trans_geno <- t( geno_matrix %>% dplyr::select(dplyr::one_of(processed_data$strain)) )
row_name <- rownames(trans_geno)

processed_data <- processed_data[processed_data$strain %in% rownames(trans_geno), ]
processed_data <- arrange(processed_data, factor(strain, levels = rownames(trans_geno)))
processed_data
```

_______________________________________
SmartPCA: pruning for strains that confound population structure

```{r}
geno_num <- geno_matrix %>%
  mutate(across(processed_data$strain, ~ case_when(
    . == "0/0" ~ 0,
    . == "0/1" ~ 1,
    . == "1/0" ~ 1,
    . == "1/1" ~ 2,
    TRUE ~ 9  # for missing or unexpected values
  )))
#geno_num

geno_mat_PCA <- as.matrix(dplyr::select(geno_num, AB1:XZ1516))
#write.table(geno_mat_PCA, "/Users/ykang/Desktop/genomat_names.txt", #genomat_for_smartpca.txt
#            row.names = FALSE, col.names = TRUE)
#geno_mat_PCA
```

```{r,fig.width=3, fig.height=3.5}
grouping <- rep("All", ncol(read.table("/Users/ykang/Desktop/genomat_for_smartpca.txt", nrows = 1)))
pca_res <- smart_pca(snp_data = "/Users/ykang/Desktop/genomat_for_smartpca.txt", 
                     sample_group = grouping, pc_axes = 5)

pca_res$pca.eigenvalues # extract eigenvalues
pca_res$pca.snp_loadings # extract principal coefficients (SNP loadings)
pca_res$pca.sample_coordinates # extract principal components (sample position in PCA space)
plot(pca_res$pca.sample_coordinates[,c("PC1","PC2")], cex = 0.3,
     pch = 19, main = "genotype smartpca")
```

```{r}
detect_pca_outliers <- function(pca_res, npc = 5, alpha = 0.975, method = c("classical", "robust"),sample_names = NULL) {
  
  method <- match.arg(method)

  if (!"pca.sample_coordinates" %in% names(pca_res)) {
    stop("The object doesn't appear to be a smart_pca result (missing pca_sample_coordinates).")
  }
  coords_df <- pca_res$pca.sample_coordinates

  # Make sure the requested PCs exist
  pccols <- paste0("PC", 1:npc)
  if (!all(pccols %in% colnames(coords_df))) {
    stop("Not enough PC columns in pca_res. Re-run smart_pca() with pc_axes >= ", npc)
  }

  # Extract numeric PC matrix
  pcmat <- as.matrix(coords_df[, pccols, drop = FALSE])

  # Compute squared Mahalanobis distances
  if (method == "classical") {
    cov_mat <- cov(pcmat, use = "pairwise.complete.obs")
    md2 <- mahalanobis(pcmat, center = colMeans(pcmat, na.rm = TRUE), cov = cov_mat)
  } else {
    if (requireNamespace("robustbase", quietly = TRUE)) {
      mcd <- robustbase::covMcd(pcmat)
      md2 <- mahalanobis(pcmat, center = mcd$center, cov = mcd$cov)
    } else if (requireNamespace("MASS", quietly = TRUE)) {
      covrob <- MASS::cov.rob(pcmat, na.action = na.omit)
      md2 <- mahalanobis(pcmat, center = covrob$center, cov = covrob$cov)
    } else {
      stop("Install 'robustbase' or 'MASS' for robust covariance estimation.")
    }
  }

  # Determine cutoff
  cutoff <- qchisq(alpha, df = npc)
  outlier_flag <- md2 > cutoff

  # Use user-provided sample names or fallback to column numbers
  if (is.null(sample_names)) {
    sample_names <- seq_len(nrow(pcmat))
  } else if (length(sample_names) != nrow(pcmat)) {
    stop("Length of sample_names does not match number of samples in pca_res")
  }

  # Output table
  res <- data.frame(
    sample = sample_names,
    md2 = md2,
    outlier = outlier_flag,
    stringsAsFactors = FALSE
  )

  message(sum(outlier_flag), " outliers detected (method = ", method, ", alpha = ", alpha, ")")

  # Return list including sample/strain names
  list(
    results = res,
    outlier_strains = res$sample[outlier_flag],
    outlier_indices = which(outlier_flag),
    cutoff = cutoff,
    method = method,
    npc = npc
  )
}

# Small helper: %||% operator
`%||%` <- function(x, y) if (!is.null(x)) x else y
```

```{r}
out_robust <- detect_pca_outliers(pca_res, npc = 5, method = "classical", alpha = 0.975,
                                  sample_names=colnames(geno_mat_PCA))
out_robust$results[out_robust$outlier_indices, ]
plot(pca_res$pca.sample_coordinates[,c("PC1","PC2")], cex = 0.3,
     pch = 19, main = "genotype smartpca")
points(pca_res$pca.sample_coordinates[,c("PC1","PC2")][out_robust$outlier_indices, ], cex = 0.3,
     pch = 19, col='red', add=TRUE)
plot(pca_res$pca.sample_coordinates[,c("PC1","PC2")][setdiff(seq(1,ncol(geno_mat_PCA)),out_robust$outlier_indices), ], cex = 0.3,pch = 19, main = "outlier removed")
```

```{r}
#if you want to repeat pruning multiple times.
n = 4
outlierlist = list()
outlierlist = vector("list", length = n)

remove_ind_list = out_robust$outlier_indices

for (i in 1:n) {
  pca_filtered <- smart_pca(
  snp_data = "/Users/ykang/Desktop/genomat_for_smartpca.txt",
  sample_group = grouping,
  sample_remove = remove_ind_list,
  pc_axes = 5 )
  
  out_robust_fin <- detect_pca_outliers(pca_filtered, npc = 5, method = "classical", alpha = 0.975,
                                        sample_names=colnames(geno_mat_PCA))

  outlierlist[[i]] <- out_robust_fin$results[out_robust_fin$outlier_indices, ]
  
  remove_ind_list <- c(remove_ind_list, out_robust_fin$outlier_indices)
}

outliers_df = do.call(rbind, outlierlist)
outliers_df
```

___
```{r}
processed_data <- processed_data[processed_data$strain %in% colnames(A), ]
processed_data <- arrange(processed_data, factor(strain, levels = colnames(A)))
processed_data
```

```{r}
# Broad-sense heritability H^2

H2.test.boot <- function(data, indicies){
    
    d <- data[indicies,]
    pheno <- as.data.frame(dplyr::select(d, Value))[,1]
    strain <- as.factor(d$strain)
    
    reffMod <- lme4::lmer(pheno ~ 1 + (1|strain))
    
    Variances <- as.data.frame(lme4::VarCorr(reffMod, comp = "Variance"))
    
    Vg <- Variances$vcov[1]
    Ve <- Variances$vcov[2]
    H2 <- Vg/(Vg+Ve)
    
     errors <- sqrt(diag(lme4::VarCorr(reffMod, comp = "Variance")$strain))
    
    return(H2)
}

## data is data frame that contains strain and Value column
H2.test <- function(data){
  
    d <- data[indicies,]    
    pheno <- as.data.frame(dplyr::select(data, Value))[,1]
    strain <- as.factor(data$strain)
    
    reffMod <- lme4::lmer(pheno ~ 1 + (1|strain))
    
    Variances <- as.data.frame(lme4::VarCorr(reffMod, comp = "Variance"))
    
    Vg <- Variances$vcov[1]
    Ve <- Variances$vcov[2]
    H2 <- Vg/(Vg+Ve)
    
     errors <- sqrt(diag(lme4::VarCorr(reffMod, comp = "Variance")$strain))
    
    return(H2)
}
```

```{r}
# Narrow sense heritability h^2

narrowh2.boot <- function(data, indicies){
    
    d <- data[indicies,]
    strain <- as.factor(d$strain)
    
    h2_res <- sommer::mmes(fixed = Value ~ 1, random = ~vsm(ism(strain), Gu=A), data = d)
    #h2_res <- sommer::mmes(Value ~ 1, random = ~sommer::vsm(strain, Gu = A), data = d)
    #h2_res <- sommer::mmer(Value ~ 1, random = ~sommer::vsr(strain, Gu = A), data = d)
    
    h2 <- as.numeric(sommer::vpredict(h2_res, h2 ~ (V1) / (V1+V2))[[1]][1])
    
    return(h2)
    
}

# narrow sense heritability with sommer::mmer (no bootstrap)
narrowh2 <- function(df_h){
  
    strain <- as.factor(d$strain)
    
    h2_res <- sommer::mmes(fixed = Value ~ 1, random = ~vsm(ism(strain), Gu=A), data = df_h)
    #h2_res <- sommer::mmer(Value ~ 1, random = ~sommer::vsr(strain, Gu = A), data = df_h)
    
    h2 <- as.numeric(sommer::vpredict(h2_res, h2 ~ (V1) / (V1+V2))[[1]][1])
    
    return(h2)
    
}
```

```{r}
# heritablility function

H2.calc <- function(data, boot = TRUE, type = "broad", reps = 2000){
    df <- dplyr::select(data, strain, Value)
    
    if(boot == TRUE){
        # if you Error in bca.ci(boot.out, conf, index[1L], L = L, t = t.o, t0 = t0.o,  : estimated adjustment 'a' is NA, then you need to increase reps value.
        if(type == "broad") {
            results <- boot::boot(data = df, statistic = H2.test.boot, R = reps) 
        } else {
            results <- boot::boot(data = df, statistic = narrowh2.boot, R = reps) 
        }
        
        # get 95% confidence interval
        ci <- boot.ci(results, type="all")  #type="bca"
        
        H2_errors <- data.frame(H2 = ci$t0,
                                ci_l = ci$bca[4],
                                ci_r = ci$bca[5])
        
        return(H2_errors)
        
    } else {
        if(type == "broad") {
            H2 <- data.frame(H2 = H2.test(data = df), ci_l = NA, ci_r = NA)
        } else {
            H2 <- data.frame(H2 = narrowh2(df_h = df), ci_l = NA, ci_r = NA)
        }
        return(H2)
    }
    
}
```

```{r}
test <- processed_data %>%
    dplyr::group_by(strain) %>%
    dplyr::summarize(num = dplyr::n()) %>%
    dplyr::filter(num > 2)

nrow(test)

0.8*length(unique(processed_data$strain))

# if nrow(test) >= 0.8*length(unique(processed_data$strain)), strains have enough replicates. 
# can try bootstrapping for CI.
```

_______________________________________
Estimating variance explained by GWAS QTL

```{r}
rm(geno_matrix)
geno_matrix <- readLines("/Volumes/YounJaeSSD/2021_MaxPlanck/laptop/YJ_writing/Evo_Agg_paper/V2/code/files/Genotype_Matrix.tsv")
geno_matrix <- stringr::str_replace_all(geno_matrix, "t", "")  #getting rid of "t" tap separator.
geno_matrix <- textConnection(geno_matrix)
geno_matrix <- read.delim(geno_matrix, sep="\\") %>% na.omit()

geno_matrix[geno_matrix=="0/0"] <- 0
geno_matrix[geno_matrix=="0/1"] <- 1
geno_matrix[geno_matrix=="1/1"] <- 2
geno_matrix
```

```{r}
geno_matrix <- read.table("/Users/yjkang/Desktop/Evo_Agg/new_genotype_mat/Genotype_Matrix.tsv", sep = "\t", header = TRUE)
geno_matrix
```

```{r}
compute_grm <- function(X) {
  # Calculate Alternate Allele Frequencies (p) for each SNP
  p <- apply(X, 2, function(x) mean(x, na.rm = TRUE) / 2)
  
  # Impute missing genotypes with the expected mean
  for (m in 1:ncol(X)) {
    X[is.na(X[, m]), m] <- 2 * p[m]
  }
  
  # Standardize the genotypes
  W <- sweep(X, 2, 2 * p, FUN = "-")
  denom <- sqrt(2 * p * (1 - p))
  W <- sweep(W, 2, denom, FUN = "/")
  
  # If a SNP is monomorphic (p=0 or p=1), denominator is 0. 
  # We set these to 0 to prevent NaN errors.
  W[, denom == 0 | is.na(denom)] <- 0  
  
  # Compute the Genetic Relatedness Matrix (A)
  M <- ncol(W)
  A <- (W %*% t(W)) / M
  
  return(A)
}

#compute_grm(trans_geno)
```

```{r}
M_qtl <- geno_matrix %>%
  filter(CHROM == "X", POS >= 14781111, POS <= 15763966)
trans_geno <- t( M_qtl %>% dplyr::select(dplyr::one_of(processed_data$strain)) ) #processed_data$strain #divergent_strain
row_name <- rownames(trans_geno)
trans_geno <- apply(trans_geno,2, as.numeric, header=TRUE, row.names=1)  #turning values into double.
rownames(trans_geno) <- row_name  #adding strain row header
A_qtl <- compute_grm(trans_geno) #sommer::A.mat(trans_geno)
data.frame(A_qtl)

M_bg <- geno_matrix %>%
  filter(!(CHROM == "X" & POS >= 14781111 & POS <= 15763966))
trans_geno <- t( M_bg %>% dplyr::select(dplyr::one_of(processed_data$strain)) ) #processed_data$strain
row_name <- rownames(trans_geno)
trans_geno <- apply(trans_geno,2, as.numeric, header=TRUE, row.names=1)  #turning values into double.
rownames(trans_geno) <- row_name  #adding strain row header
A_bg <- compute_grm(trans_geno) #sommer::A.mat(trans_geno)
data.frame(A_bg)
```

```{r}
scaleM <- function(M) {
  M <- scale(M, center = TRUE, scale = TRUE)
  M[is.na(M)] <- 0
  return(M) }

A_qtl <- scaleM(A_qtl)
A_bg  <- scaleM(A_bg)
A_qtl
```

```{r}
processed_data <- processed_data[processed_data$strain %in% colnames(A_bg), ]
processed_data <- arrange(processed_data, factor(strain, levels = colnames(A_bg)))
data <- processed_data[,c("strain","agg_timescale")]
colnames(data) <- c("strain", "Value")

fit <- sommer::mmes(
  fixed = Value ~ 1,  # fixed effects (intercept)
  random = ~ vsm(ism(strain), Gu = A_qtl) +  # QTL effect
             vsm(ism(strain), Gu = A_bg),   # Background genome
  data = data )

varcomp <- summary(fit)$varcomp
var_qtl <- varcomp["strain:A_qtl:mu:mu", "VarComp"]
var_bg    <- varcomp["strain:A_bg:mu:mu", "VarComp"]
var_res     <- varcomp["units:mu:mu", "VarComp"]

h2_QTL <- var_qtl / (var_qtl + var_bg + var_res)
h2_bg <- var_bg / (var_qtl + var_bg + var_res)
cat("Regional (QTL) h2:", round(h2_QTL, 3), "\n")
cat("Background genome h2:", round(h2_bg, 3), "\n")
```

likelihood ratio test for significance.
```{r}
fit_reduced <- sommer::mmes(
  fixed = Value ~ 1,
  random = ~ vsm(ism(strain), Gu = A_bg),
  data = data )

LRT <- 2 * (fit$llik - fit_reduced$llik[1:length(fit$llik)])
pval <- pchisq(LRT, df = 1, lower.tail = FALSE) / 2  # boundary-corrected

cat("LRT =", round(LRT, 3), " | p =", signif(pval, 3), "\n")
```

_______________________________________
genes found in the QTL

```{r}
library(gggenomes)
bed_df <- read_bed("/Users/ykang/Desktop/X-AggTimev2_QTL_genes.bed")  #AggMagQTL_genes.bed
bed_df
```
```{r}
bed_df$name
```

